name: Buildtest Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - shahzebsiddiqui
body:
  - type: markdown
      value: "## Thank you for contributing to buildtest!"
